//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAndSolutions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devision()
        {
            this.Worker = new HashSet<Worker>();
        }
    
        public short ID_Devision { get; set; }
        public string DevName { get; set; }
        public string HeadOffice { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker> Worker { get; set; }

        public string GetStatus
        {
            get
            {
                if ((bool)Status)
                    return "Действует";
                else
                    return "Закрыт";
            }
        }
    }
}
